export enum Stack {
  TYPESCRIPT = 'typescript',
  TYPEORM = 'typeOrm',
  NEST_JS = 'nestJs',
  NODE_JS = 'nodeJs',
  REACT = 'react',
  REACT_NATIVE = 'reactNative',
  MYSQL = 'mySql',
  DOCKER = 'docker',
  DOCTRINE_ORM = 'doctrineOrm',
  KUBERNETES = 'kubernetes',
  FIREBASE = 'firebase',
  IOS = 'ios',
  ANDROID = 'android',
  REDUX = 'redux',
  JAVASCRIPT = 'javaScript',
  EXPRESS_JS = 'expressJs',
  API = 'api',
  PHP = 'php',
  PHPSTAN = 'phpstan',
  SYMFONY = 'symfony',
  STIMULUS = 'stimulus',
  TWIG = 'twig',
  HTML = 'html',
  CSS = 'css',
  SCSS = 'scss',
  BOOTSTRAP = 'bootstrap',
  BUN = 'bun',
  TAILWIND_CSS = 'tailwindCss',
  PHOTOSHOP = 'photoshop',
  ILLUSTRATOR = 'illustrator',
  INDESIGN = 'inDesign',
  AFTER_EFFECTS = 'afterEffects',
  THREE_DS_MAX = '3dsMax',
  VITE = 'vite',
  WEBPACK = 'webpack',
  FIGMA = 'figma',
}

export const StackI18n: Record<Stack, string> = {
  [Stack.TYPESCRIPT]: 'TypeScript',
  [Stack.TYPEORM]: 'TypeORM',
  [Stack.NEST_JS]: 'NestJS',
  [Stack.NODE_JS]: 'Node.js',
  [Stack.REACT]: 'React',
  [Stack.REACT_NATIVE]: 'React Native',
  [Stack.MYSQL]: 'MySQL',
  [Stack.DOCKER]: 'Docker',
  [Stack.DOCTRINE_ORM]: 'DoctrineORM',
  [Stack.KUBERNETES]: 'Kubernetes',
  [Stack.FIREBASE]: 'Firebase',
  [Stack.IOS]: 'iOS',
  [Stack.ANDROID]: 'Android',
  [Stack.REDUX]: 'Redux',
  [Stack.JAVASCRIPT]: 'JavaScript',
  [Stack.EXPRESS_JS]: 'Express JS',
  [Stack.API]: 'API',
  [Stack.PHP]: 'PHP',
  [Stack.PHPSTAN]: 'PHPStan',
  [Stack.SYMFONY]: 'Symfony',
  [Stack.STIMULUS]: 'Stimulus',
  [Stack.TWIG]: 'Twig',
  [Stack.HTML]: 'HTML',
  [Stack.CSS]: 'CSS',
  [Stack.SCSS]: 'SCSS',
  [Stack.BOOTSTRAP]: 'Bootstrap',
  [Stack.BUN]: 'Bun',
  [Stack.TAILWIND_CSS]: 'Tailwind CSS',
  [Stack.PHOTOSHOP]: 'Photoshop',
  [Stack.ILLUSTRATOR]: 'Illustrator',
  [Stack.INDESIGN]: 'InDesign',
  [Stack.AFTER_EFFECTS]: 'After Effects',
  [Stack.THREE_DS_MAX]: '3DS Max',
  [Stack.VITE]: 'Vite',
  [Stack.WEBPACK]: 'Webpack',
  [Stack.FIGMA]: 'Figma',
};

export const StackColor: Record<Stack, string> = {
  [Stack.TYPESCRIPT]: '#3178c6',
  [Stack.TYPEORM]: '#E05C2D',
  [Stack.NEST_JS]: '#EA2845',
  [Stack.NODE_JS]: '#68A063',
  [Stack.REACT]: '#61dbfb',
  [Stack.REACT_NATIVE]: '#61dbfb',
  [Stack.MYSQL]: '#00678C',
  [Stack.DOCKER]: '#2496ed',
  [Stack.DOCTRINE_ORM]: '#005C99',
  [Stack.KUBERNETES]: '#326CE5',
  [Stack.FIREBASE]: '#FFCA28',
  [Stack.IOS]: '#aaaaaa',
  [Stack.ANDROID]: '#a4c639',
  [Stack.REDUX]: '#764ABC',
  [Stack.JAVASCRIPT]: '#d4b62f',
  [Stack.EXPRESS_JS]: '#aaaaaa',
  [Stack.API]: '#aaaaaa',
  [Stack.PHP]: '#8892be',
  [Stack.PHPSTAN]: '#3B8C4A',
  [Stack.SYMFONY]: '#aaaaaa',
  [Stack.STIMULUS]: '#2CC0A0',
  [Stack.TWIG]: '#E67E22',
  [Stack.HTML]: '#e34c26',
  [Stack.CSS]: '#264de4',
  [Stack.SCSS]: '#c6538c',
  [Stack.BOOTSTRAP]: '#7952b3',
  [Stack.BUN]: '#FF6B6B',
  [Stack.TAILWIND_CSS]: '#06b6d4',
  [Stack.PHOTOSHOP]: '#56a1d8',
  [Stack.ILLUSTRATOR]: '#f89a1c',
  [Stack.INDESIGN]: '#ee3a68',
  [Stack.AFTER_EFFECTS]: '#9696ca',
  [Stack.THREE_DS_MAX]: '#09a1a1',
  [Stack.VITE]: '#BD34FE',
  [Stack.WEBPACK]: '#8DD6F9',
  [Stack.FIGMA]: '#f24e1e',
};
